# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pavt.github.io',
                'doc_host': 'https://pavt.github.io',
                'git_url': 'https://github.com/pavt/pavt.github.io',
                'lib_path': 'pavt.github.io'},
  'syms': {'pavt.github.io.core': {'pavt.github.io.core.foo': ('core.html#foo', 'pavt.github.io/core.py')}}}
