project:
  type: website

format:
  html:
    theme:
      light: cosmo
    css: styles.css
    toc: true


website:
  twitter-card: true
  open-graph: true
  
  navbar:
    navbar-width: 350px
    background: light
    search: true
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]